services:
  - type: web
    name: rutinas-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free # Postgres externo (Neon/Supabase), sin disco
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_NAME
        value: Rutinas
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false # ej: ep-xxxx.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        sync: false # ej: neondb
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: LOG_CHANNEL
        value: errorlog
